### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by shelomentsevd** [shelomentsevd/chat#1]
- [x] ⭐️ authorization
- [x] ⭐️ POST /chats route
- [x] ✅ tests for POST /chats
- [x] ⭐️ GET /chats
- [x] ✅ tests for GET /chats
- [x] ⭐️ GET /chats/ID
- [x] ✅ tests for GET /chats/ID
- [x] ⭐️ POST /chats/ID/join
- [x] ✅ tests for POST /chats/ID/join
- [x] ⭐️ POST /chats/ID/leave
- [x] ✅ tests for POST /chats/ID/leave
- [x] ⭐️ POST /chats/ID/messages route
- [x] ✅ tests for POST /chats/ID/messages route
- [x] ⭐️ GET /chats/ID/messages route
- [x] ✅ tests for GET /chats/ID/messages route
- [x] ⭐️ GET /chats/ID/messages/ID route
- [x] ✅ tests for GET /chats/ID/messages/ID route
- [x] ⭐️ GET /users
- [x] ✅ tests for GET /users
- [x] ⭐️  GET /chats/ID/users
- [x] ✅  tests for GET /chats/ID/users
- [x] ⭐️ /registration route
- [x] ✅ tests for /registration
- [x] ⭐️ database connection
- [x] ⭐️ json api
- [x] 🐋 docker-compose file
